# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["kat.marchan@fastly.com"]
description = "example of using the cpp sdk"
language = "other"
manifest_version = 3
name = "cpp-example"
service_id = ""

[local_server]
backends.fastly.url = "https://www.fastly.com"
backends.wikipedia.url = "https://en.wikipedia.org"