# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["kat.marchan@fastly.com"]
description = "example of using the cpp sdk"
language = "other"
manifest_version = 3
name = "cpp-example"
service_id = ""

[local_server]
[local_server.backends]
fastly.url = "https://www.fastly.com"
wikipedia.url = "https://en.wikipedia.org"
esi-cpp-demo.url = "https://esi-cpp-demo.edgecompute.app"

[local_server.config_stores.example-store]
format = "inline-toml"

[local_server.config_stores.example-store.contents]
hello = "world"
