# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

name = "quickstart-cpp"
authors = ["you@example.com"]
description = "Quickstart app for the C++ Fastly Compute SDK"
# For now
language = "other"
manifest_version = 3
service_id = ""

[local_server]
backends.example.url = "https://www.example.com"
