name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RUSTFLAGS: -Dwarnings
  DOCS_FASTLY_API_TOKEN: ${{ secrets.DOCS_FASTLY_API_TOKEN }}
  DOCS_FASTLY_SERVICE_ID: ${{ vars.DOCS_FASTLY_SERVICE_ID }}
  DOCS_FASTLY_KVSTORE_NAME: ${{ vars.DOCS_FASTLY_KVSTORE_NAME }}

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Check Rust Format
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Install WASI SDK
        uses: konsumer/install-wasi-sdk@v1
        with:
          version: "25"
      - name: Run clippy
        run: cargo clippy --all -- -D warnings

  clangfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install WASI SDK
        uses: konsumer/install-wasi-sdk@v1
        with:
          version: "25"
      - name: Check C++ Format
        run: /opt/wasi-sdk/bin/clang-format --dry-run --Werror include/**/*.h src/**/*.h src/**/*.cpp

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Viceroy
        run: cargo install viceroy --locked

      - name: Install WASI SDK
        uses: konsumer/install-wasi-sdk@v1
        with:
          version: "25"

      - uses: extractions/setup-just@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build WebAssembly module
        run: just

      - name: Run tests
        run: just test

      - name: Build docs
        uses: mattnotmitt/doxygen-action@v1.9.5

      - name: Deploy docs
        if: github.ref == 'refs/heads/main'
        env:
          FASTLY_API_TOKEN: ${{ env.DOCS_FASTLY_API_TOKEN }}
        run: |
          npx -y @fastly/compute-js-static-publish@7 --root-dir=./docs --output=./docs-compute-cpp --service-id=${{ env.DOCS_FASTLY_SERVICE_ID }} --kv-store-name=${{ env.DOCS_FASTLY_KVSTORE_NAME }}
          cd ./docs-compute-cpp
          npm install
          npm run fastly:publish
