name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install WASI SDK
        uses: konsumer/install-wasi-sdk@v1
        with:
          version: "25"

      - uses: extractions/setup-just@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build WebAssembly module
        run: just

      - name: Build docs
        uses: mattnotmitt/doxygen-action@v1.9.5

      - name: Archive core dist
        run: tar cvf fastly-compute-sdk-cpp.tar -C target/release/dist fastly libfastly.a

      - name: Archive quickstart dist
        run: tar cvf fastly-compute-sdk-cpp-quickstart.tar -C target/release/dist fastly libfastly.a

      - name: Add docs and license to quickstart dist
        run: tar rvf fastly-compute-sdk-cpp-quickstart.tar docs LICENSE

      - name: Add quickstart files to quickstart dist
        run: tar rvf fastly-compute-sdk-cpp-quickstart.tar -C quickstart CMakeLists.txt fastly.toml main.cpp README.md

      - name: Gzip core dist
        run: gzip fastly-compute-sdk-cpp.tar

      - name: Gzip quickstart dist
        run: gzip fastly-compute-sdk-cpp-quickstart.tar

      - uses: ncipollo/release-action@v1
        with:
          artifacts: fastly-compute-sdk-cpp*.tar.gz
          artifactErrorsFailBuild: true
          artifactContentType: "application/gzip"
          generateReleaseNotes: true
          draft: true
          prerelease: true
